# Generated by Django 5.0.6 on 2024-06-01 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_pic',
            new_name='pic',
        ),
    ]
