# Generated by Django 5.0.6 on 2024-06-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_rename_profile_pic_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(blank=True, default='Default.png', null=True, upload_to='media/'),
        ),
    ]
